### ISSUE TITLE
Enhance time complexity of PowerLinear file from Linear to Logrithmic

### ISSUE THREAD

**Issue by codea-holic** [codea-holic/online-java-foundation#4]
**Reduce its time complexity from Linear to logarithmic time.**

This file is added with _commit id_ 01ee94f500520d903f57e9f56fbc32ea5d151634

**Comment by h-asawa** [comment]
[PowerRecursion.txt](https://github.com/codea-holic/online-java-foundation/files/6478135/PowerRecursion.txt)
Fixes #4

**Comment by h-asawa** [comment]
Is this okay? @codea-holic

**Comment by codea-holic** [comment]
Perfect

**Comment by codea-holic** [comment]
Make a pull request and commit these changes also.
